// Integrated client script with backend API usage
let balance = 10000, currentBet = null, currentGame = null, previousFocus = null, transactions = [];
let currentUser = null, isAuthenticated = false, achievements = [], gameHistory = [], dailyBonusClaimed = false;
let slotsState = { spinning: false }, rouletteState = { spinning: false, selectedBet: null }, blackjackState = { gameState: null };

document.addEventListener('DOMContentLoaded', () => { setupEventListeners(); initNavToggle(); initRevealObserver(); initTiltEffects(); initFinanceButtons(); initAuthSystem(); initModalTriggers(); initHeroMetrics(); initLiveTicker(); initSpotlightCountdown(); initHeatmapBars(); bootstrapFromServer(); });

async function bootstrapFromServer(){ showLoader(); try { if(apiClient.isAuthenticated()){ await loadUserDataFromServer(); await refreshBalance(); await initDailyBonusUI(); await loadTransactions(); } else { updateBalance(); initDailyBonusUI(); } } catch(e){ console.warn('Bootstrap fallback', e.message); updateBalance(); } finally { hideLoader(); }}

function setupEventListeners(){ document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault(); const t=document.querySelector(a.getAttribute('href')); if(t) t.scrollIntoView({behavior:'smooth'});})); window.addEventListener('scroll', updateActiveNav); }
function initNavToggle(){ const toggle=document.getElementById('navToggle'); const navLinks=document.getElementById('primaryNav'); const overlay=document.getElementById('navOverlay'); if(!toggle||!navLinks||!overlay) return; document.body.classList.add('mobile-nav-ready'); const closeMenu=()=>{ navLinks.classList.remove('open'); toggle.classList.remove('active'); toggle.setAttribute('aria-expanded','false'); overlay.classList.remove('visible'); overlay.setAttribute('aria-hidden','true'); document.body.classList.remove('nav-menu-open'); }; const openMenu=()=>{ navLinks.classList.add('open'); toggle.classList.add('active'); toggle.setAttribute('aria-expanded','true'); overlay.classList.add('visible'); overlay.setAttribute('aria-hidden','false'); document.body.classList.add('nav-menu-open'); }; closeMenu(); toggle.addEventListener('click',()=>{ const isOpen=navLinks.classList.contains('open'); if(isOpen) closeMenu(); else openMenu(); }); overlay.addEventListener('click',closeMenu); navLinks.querySelectorAll('a, button').forEach(link=>{ link.addEventListener('click',()=>{ if(window.innerWidth<=1024) closeMenu(); }); }); window.addEventListener('resize',()=>{ if(window.innerWidth>1024) closeMenu(); }); }
function scrollToGames(){ const gamesSection=document.getElementById('games'); if(gamesSection) gamesSection.scrollIntoView({ behavior:'smooth', block:'start' }); }
function initFinanceButtons(){ const dep=document.getElementById('depositBtn'); const wit=document.getElementById('withdrawBtn'); if(dep) dep.addEventListener('click',()=>openFinance('deposit')); if(wit) wit.addEventListener('click',()=>openFinance('withdraw')); }
function initModalTriggers(){ document.querySelectorAll('[data-modal]').forEach(btn=>btn.addEventListener('click',()=>openGenericModal(btn.dataset.modal))); document.querySelectorAll('.close[data-close]').forEach(c=>c.addEventListener('click',()=>closeGenericModal(c.dataset.close))); }
function openGenericModal(id){ const m=document.getElementById(id); if(!m) return; m.style.display='block'; m.classList.add('fade-in'); const c=m.querySelector('.modal-content'); if(c) c.classList.add('scale-in'); document.body.style.overflow='hidden'; m.setAttribute('aria-hidden','false'); previousFocus=document.activeElement; trapFocus(m); if(id==='achievementsModal') renderAchievements(); if(id==='leaderboardModal') renderLeaderboard('profit'); if(id==='statsModal') renderStats(); }
function closeGenericModal(id){ const m=document.getElementById(id); if(!m) return; m.style.display='none'; document.body.style.overflow='auto'; m.setAttribute('aria-hidden','true'); releaseFocus(); }
function updateActiveNav(){ const sections=document.querySelectorAll('section[id]'); const navLinks=document.querySelectorAll('.nav-link'); let current=''; sections.forEach(s=>{ if(window.pageYOffset>=s.offsetTop-200) current=s.id; }); navLinks.forEach(l=>{ l.classList.remove('active'); if(l.getAttribute('href')===`#${current}`) l.classList.add('active'); }); const nav=document.querySelector('.navbar'); if(nav){ if(window.scrollY>50) nav.classList.add('nav-shrink'); else nav.classList.remove('nav-shrink'); }}
function updateBalance(){ const el=document.getElementById('balance'); if(el) el.textContent=`$${balance.toLocaleString()}`; }
async function refreshBalance(){ if(!apiClient.isAuthenticated()) return updateBalance(); try { const d=await apiClient.getBalance(); balance=d.balance; updateBalance(); } catch(e){ console.error('Balance fetch failed', e); }}

function openGame(gameName){ currentGame=gameName; const m=document.getElementById(`${gameName}Modal`); if(!m) return; m.style.display='block'; m.classList.add('fade-in'); const c=m.querySelector('.modal-content'); if(c) c.classList.add('scale-in'); document.body.style.overflow='hidden'; m.setAttribute('aria-hidden','false'); previousFocus=document.activeElement; trapFocus(m); if(gameName==='blackjack') resetBlackjackLocal(); }
function closeGame(gameName){ const m=document.getElementById(`${gameName}Modal`); if(!m) return; m.style.display='none'; document.body.style.overflow='auto'; currentGame=null; m.setAttribute('aria-hidden','true'); releaseFocus(); m.querySelectorAll('.win-message').forEach(msg=>{ msg.textContent=''; msg.className='win-message'; }); }
function openFinance(action){ const m=document.getElementById('financeModal'); if(!m) return; m.style.display='block'; m.classList.add('fade-in'); const c=m.querySelector('.modal-content'); if(c) c.classList.add('scale-in'); document.body.style.overflow='hidden'; m.setAttribute('aria-hidden','false'); previousFocus=document.activeElement; trapFocus(m); switchFinanceTab(action); updateTransactionList(); }
function closeFinance(){ const m=document.getElementById('financeModal'); if(!m) return; m.style.display='none'; document.body.style.overflow='auto'; m.setAttribute('aria-hidden','true'); releaseFocus(); const msg=document.getElementById('financeMessage'); if(msg){ msg.textContent=''; msg.className='win-message'; } }
function switchFinanceTab(action){ const dep=document.getElementById('depositForm'); const wit=document.getElementById('withdrawForm'); const tabDep=document.getElementById('tab-deposit'); const tabWit=document.getElementById('tab-withdraw'); if(!dep||!wit||!tabDep||!tabWit) return; const msg=document.getElementById('financeMessage'); if(msg){ msg.textContent=''; msg.className='win-message'; } if(action==='deposit'){ dep.classList.remove('hidden'); wit.classList.add('hidden'); tabDep.classList.add('active'); tabWit.classList.remove('active'); } else { wit.classList.remove('hidden'); dep.classList.add('hidden'); tabWit.classList.add('active'); tabDep.classList.remove('active'); }}
// Focus helper: focus and select first visible input inside modal
function focusFirstInput(modal){ try{ if(!modal) return; const selector='input,select,textarea,button'; const inputs=Array.from(modal.querySelectorAll(selector)).filter(el=>el.offsetParent!==null && !el.disabled); if(inputs.length){ const first=inputs[0]; first.focus(); if(typeof first.select==='function') first.select(); } }catch(e){console.warn('focusFirstInput failed',e);} }

// Improve finance tab switching to focus the active input
const _origSwitchFinanceTab = switchFinanceTab;
function switchFinanceTab(action){
	const dep=document.getElementById('depositForm');
	const wit=document.getElementById('withdrawForm');
	const tabDep=document.getElementById('tab-deposit');
	const tabWit=document.getElementById('tab-withdraw');
	if(!dep||!wit||!tabDep||!tabWit) return;
	const msg=document.getElementById('financeMessage');
	if(msg){ msg.textContent=''; msg.className='win-message'; }
	if(action==='deposit'){
		dep.classList.remove('hidden');
		wit.classList.add('hidden');
		tabDep.classList.add('active');
		tabWit.classList.remove('active');
		focusFirstInput(dep);
	} else {
		wit.classList.remove('hidden');
		dep.classList.add('hidden');
		tabWit.classList.add('active');
		tabDep.classList.remove('active');
		focusFirstInput(wit);
	}
}
async function handleDeposit(e){ e.preventDefault(); const amtInput=document.getElementById('depositAmount'); const msg=document.getElementById('financeMessage'); const raw=parseInt(amtInput.value); if(isNaN(raw)||raw<10){ msg.textContent='Minimum deposit is $10.'; msg.className='win-message lose'; return;} if(!apiClient.isAuthenticated()){ msg.textContent='Login required'; msg.className='win-message lose'; return;} showLoader(); try { const r=await apiClient.deposit(raw); balance=r.balance; updateBalance(); msg.textContent=`Deposited $${raw.toLocaleString()}.`; msg.className='win-message win'; if(raw>=1000) createConfetti(); await loadTransactions(); } catch(err){ msg.textContent=err.message||'Deposit failed'; msg.className='win-message lose'; } finally { hideLoader(); }}
async function handleWithdraw(e){ e.preventDefault(); const amtInput=document.getElementById('withdrawAmount'); const msg=document.getElementById('financeMessage'); const raw=parseInt(amtInput.value); if(isNaN(raw)||raw<10){ msg.textContent='Minimum withdrawal is $10.'; msg.className='win-message lose'; return;} if(!apiClient.isAuthenticated()){ msg.textContent='Login required'; msg.className='win-message lose'; return;} showLoader(); try { const r=await apiClient.withdraw(raw); balance=r.balance; updateBalance(); msg.textContent=`Withdrew $${raw.toLocaleString()}.`; msg.className='win-message win'; await loadTransactions(); } catch(err){ msg.textContent=err.message||'Withdrawal failed'; msg.className='win-message lose'; } finally { hideLoader(); }}
async function loadTransactions(){ if(!apiClient.isAuthenticated()) return; try { const d=await apiClient.getTransactions(15,0); transactions=d.transactions.map(t=>({type:t.type, amount:Math.abs(t.amount), time:t.created_at||Date.now()})); updateTransactionList(); } catch(e){ console.error('Transactions failed', e); }}
function updateTransactionList(){ const list=document.getElementById('transactionList'); if(!list) return; list.innerHTML=''; transactions.slice(0,15).forEach(tx=>{ const li=document.createElement('li'); li.className=tx.type; const date=new Date(tx.time); const stamp=date.toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'}); li.innerHTML=`<span>${tx.type==='deposit'?'➕':tx.type==='withdraw'?'➖':'★'} $${tx.amount.toLocaleString()}</span><span>${stamp}</span>`; list.appendChild(li); }); }
window.addEventListener('click',e=>{ if(e.target.classList&&e.target.classList.contains('modal')){ e.target.style.display='none'; document.body.style.overflow='auto'; currentGame=null; e.target.setAttribute('aria-hidden','true'); releaseFocus(); if(e.target.id==='financeModal'){ const msg=document.getElementById('financeMessage'); if(msg){ msg.textContent=''; msg.className='win-message'; } } } });
window.addEventListener('keydown',e=>{ if(e.key==='Escape'&&currentGame) closeGame(currentGame); else if(e.key==='Escape'){ const fm=document.getElementById('financeModal'); if(fm&&fm.style.display==='block') closeFinance(); }});
function trapFocus(modal){ const selectors='button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])'; const f=Array.from(modal.querySelectorAll(selectors)).filter(el=>!el.disabled&&el.offsetParent!==null); if(f.length){ f[0].focus(); modal.addEventListener('keydown',handleTrap); modal.__focusables=f; }}
function handleTrap(e){ if(e.key!=='Tab') return; const f=e.currentTarget.__focusables||[]; const first=f[0]; const last=f[f.length-1]; if(e.shiftKey&&document.activeElement===first){ e.preventDefault(); last.focus(); } else if(!e.shiftKey&&document.activeElement===last){ e.preventDefault(); first.focus(); }}
function releaseFocus(){ const open=document.querySelector('.modal[aria-hidden="false"]'); if(open) open.removeEventListener('keydown',handleTrap); if(previousFocus) previousFocus.focus(); previousFocus=null; }

async function spinSlots(){ if(slotsState.spinning) return; const bet=parseInt(document.getElementById('slotBet').value); const wm=document.getElementById('slotWinMessage'); if(!apiClient.isAuthenticated()){ wm.textContent='Login required'; wm.className='win-message lose'; return;} slotsState.spinning=true; const btn=document.getElementById('spinBtn'); btn.disabled=true; wm.textContent=''; wm.className='win-message'; showLoader(); try { const res=await apiClient.playSlots(bet); ['reel1','reel2','reel3'].forEach((id,i)=>{ const el=document.getElementById(id); if(el) el.textContent=res.reels[i]; }); balance=res.balance; updateBalance(); updateFairness(res.seed,res.hash); if(res.winAmount>0){ wm.textContent=`You won $${res.winAmount.toLocaleString()}!`; wm.className='win-message win'; if(res.outcome==='jackpot') createConfetti(); } else { wm.textContent='Better luck next time!'; wm.className='win-message lose'; } updateXPFromProgression(res.progression,res.xpGained); achievements=res.achievements||achievements; } catch(err){ wm.textContent=err.message||'Spin failed'; wm.className='win-message lose'; } finally { hideLoader(); slotsState.spinning=false; btn.disabled=false; }}
function placeBet(color){ if(rouletteState.spinning) return; rouletteState.selectedBet=color; document.querySelectorAll('.bet-btn').forEach(b=>b.classList.remove('active')); event.target.classList.add('active'); }
async function spinRoulette(){ if(rouletteState.spinning) return; const wm=document.getElementById('rouletteWinMessage'); if(!rouletteState.selectedBet){ wm.textContent='Select a bet!'; wm.className='win-message lose'; return;} if(!apiClient.isAuthenticated()){ wm.textContent='Login required'; wm.className='win-message lose'; return;} const bet=parseInt(document.getElementById('rouletteBet').value); rouletteState.spinning=true; const wheel=document.getElementById('rouletteWheel'); wheel.classList.add('spinning'); wm.textContent=''; wm.className='win-message'; showLoader(); try { const res=await apiClient.playRoulette(bet,rouletteState.selectedBet); wheel.classList.remove('spinning'); balance=res.balance; updateBalance(); updateFairness(res.seed,res.hash); if(res.winAmount>0){ wm.textContent=`You won $${res.winAmount.toLocaleString()}! Result: ${res.result}`; wm.className='win-message win'; if(res.result==='green') createConfetti(); } else { wm.textContent=`Result: ${res.result.toUpperCase()} - Better luck next time!`; wm.className='win-message lose'; } updateXPFromProgression(res.progression,res.xpGained); achievements=res.achievements||achievements; } catch(err){ wheel.classList.remove('spinning'); wm.textContent=err.message||'Spin failed'; wm.className='win-message lose'; } finally { hideLoader(); rouletteState.spinning=false; rouletteState.selectedBet=null; document.querySelectorAll('.bet-btn').forEach(b=>b.classList.remove('active')); }}

function resetBlackjackLocal(){ blackjackState.gameState=null; ['playerCards','dealerCards'].forEach(id=>document.getElementById(id).innerHTML=''); document.getElementById('playerScore').textContent=''; document.getElementById('dealerScore').textContent=''; const wm=document.getElementById('blackjackWinMessage'); wm.textContent=''; wm.className='win-message'; document.getElementById('dealBtn').disabled=false; document.getElementById('hitBtn').disabled=true; document.getElementById('standBtn').disabled=true; }
async function dealCards(){ const bet=parseInt(document.getElementById('blackjackBet').value); const wm=document.getElementById('blackjackWinMessage'); if(!apiClient.isAuthenticated()){ wm.textContent='Login required'; wm.className='win-message lose'; return;} showLoader(); try { const res=await apiClient.dealBlackjack(bet); balance=res.balance; updateBalance(); blackjackState.gameState=res.gameState; currentBet=bet; renderBlackjackHands(true); updateFairness(res.gameState.seed,res.gameState.hash); document.getElementById('dealBtn').disabled=true; document.getElementById('hitBtn').disabled=false; document.getElementById('standBtn').disabled=false; updateXPFromProgression(res.progression,res.xpGained); } catch(err){ wm.textContent=err.message||'Deal failed'; wm.className='win-message lose'; } finally { hideLoader(); }}
async function hit(){ const wm=document.getElementById('blackjackWinMessage'); if(!blackjackState.gameState) return; showLoader(); try { const res=await apiClient.hitBlackjack(blackjackState.gameState); blackjackState.gameState=res.gameState; renderBlackjackHands(false); if(res.outcome==='bust'){ wm.textContent='Bust! You lose.'; wm.className='win-message lose'; document.getElementById('hitBtn').disabled=true; document.getElementById('standBtn').disabled=true; document.getElementById('dealBtn').disabled=false; } } catch(err){ wm.textContent=err.message||'Hit failed'; wm.className='win-message lose'; } finally { hideLoader(); }}
async function stand(){ const wm=document.getElementById('blackjackWinMessage'); if(!blackjackState.gameState) return; showLoader(); try { const res=await apiClient.standBlackjack(blackjackState.gameState); blackjackState.gameState=res.gameState; renderBlackjackHands(false,true); balance=res.balance; updateBalance(); if(res.outcome==='win'){ wm.textContent=`You won $${res.winAmount.toLocaleString()}!`; wm.className='win-message win'; createConfetti(); } else if(res.outcome==='push'){ wm.textContent='Push! Bet returned.'; wm.className='win-message'; } else { wm.textContent='Dealer wins!'; wm.className='win-message lose'; } updateFairness(res.gameState.seed,res.gameState.hash); updateXPFromProgression(res.progression,res.xpGained); achievements=res.achievements||achievements; } catch(err){ wm.textContent=err.message||'Stand failed'; wm.className='win-message lose'; } finally { hideLoader(); document.getElementById('hitBtn').disabled=true; document.getElementById('standBtn').disabled=true; document.getElementById('dealBtn').disabled=false; }}
function renderBlackjackHands(hideDealer,revealDealer=false){ const gs=blackjackState.gameState; if(!gs) return; const pc=document.getElementById('playerCards'); const dc=document.getElementById('dealerCards'); pc.innerHTML=''; dc.innerHTML=''; gs.playerHand.forEach(c=>displayServerCard(pc,c)); gs.dealerHand.forEach((c,i)=>displayServerCard(dc,c,hideDealer&&i===0&&!revealDealer)); document.getElementById('playerScore').textContent=`Score: ${gs.playerScore}`; document.getElementById('dealerScore').textContent=`Score: ${gs.dealerScore}`; }
function displayServerCard(container,card,hidden=false){ const el=document.createElement('div'); el.className='card'; if(hidden){ el.textContent='🂠'; el.style.background='#333'; } else { const isRed=card.suit==='♥'||card.suit==='♦'; el.className+=' '+(isRed?'red':'black'); el.textContent=`${card.rank}${card.suit}`; } container.appendChild(el); }

function initAuthSystem(){ const loginBtn=document.getElementById('loginBtn'); const logoutBtn=document.getElementById('logoutBtn'); if(loginBtn) loginBtn.addEventListener('click',openAuth); if(logoutBtn) logoutBtn.addEventListener('click',handleLogout); }
async function loadUserDataFromServer(){ try { const profile=await apiClient.getProfile(); currentUser=profile.user; achievements=profile.achievements||[]; isAuthenticated=true; balance=currentUser.balance||balance; updateUserUI(); updateXPBar(); } catch(e){ console.error('Profile load failed', e); }}
function saveUserData(){}
async function handleLogin(e){ e.preventDefault(); const u=document.getElementById('loginUsername').value; const p=document.getElementById('loginPassword').value; const msg=document.getElementById('authMessage'); msg.textContent=''; msg.className='win-message'; showLoader(); try { await apiClient.login(u,p); await loadUserDataFromServer(); await refreshBalance(); isAuthenticated=true; showNotification('Login Successful',`Welcome back, ${u}!`,'success'); closeAuth(); initDailyBonusUI(); } catch(err){ msg.textContent=err.message||'Login failed'; msg.className='win-message lose'; } finally { hideLoader(); }}
async function handleSignup(e){ e.preventDefault(); const u=document.getElementById('signupUsername').value; const em=document.getElementById('signupEmail').value; const p=document.getElementById('signupPassword').value; const msg=document.getElementById('authMessage'); msg.textContent=''; msg.className='win-message'; showLoader(); try { await apiClient.register(u,em,p); await loadUserDataFromServer(); await refreshBalance(); isAuthenticated=true; showNotification('Account Created',`Welcome to Lucky Casino, ${u}!`,'success'); closeAuth(); initDailyBonusUI(); } catch(err){ msg.textContent=err.message||'Signup failed'; msg.className='win-message lose'; } finally { hideLoader(); }}
async function handleLogout(){ showLoader(); try { await apiClient.logout(); } catch(_){} currentUser=null; isAuthenticated=false; balance=10000; transactions=[]; gameHistory=[]; achievements=[]; updateUserUI(); updateBalance(); showNotification('Logged Out','See you soon!','info'); initDailyBonusUI(); hideLoader(); }
function updateUserUI(){ const loginBtn=document.getElementById('loginBtn'); const userProfile=document.getElementById('userProfile'); const userName=document.getElementById('userName'); const userLevel=document.getElementById('userLevel'); if(isAuthenticated&&currentUser){ if(loginBtn) loginBtn.style.display='none'; if(userProfile) userProfile.style.display='flex'; if(userName) userName.textContent=currentUser.username; if(userLevel) userLevel.textContent=`Level ${currentUser.level||1}`; } else { if(loginBtn) loginBtn.style.display='block'; if(userProfile) userProfile.style.display='none'; }}
function openAuth(){ const m=document.getElementById('authModal'); if(!m) return; m.style.display='block'; m.classList.add('fade-in'); document.body.style.overflow='hidden'; m.setAttribute('aria-hidden','false'); previousFocus=document.activeElement; switchAuthTab('login'); }
function closeAuth(){ const m=document.getElementById('authModal'); if(!m) return; m.style.display='none'; document.body.style.overflow='auto'; m.setAttribute('aria-hidden','true'); releaseFocus(); const msg=document.getElementById('authMessage'); if(msg){ msg.textContent=''; msg.className='win-message'; }}
function switchAuthTab(tab){ const loginForm=document.getElementById('loginForm'); const signupForm=document.getElementById('signupForm'); const tabLogin=document.getElementById('tab-login'); const tabSignup=document.getElementById('tab-signup'); const msg=document.getElementById('authMessage'); if(msg){ msg.textContent=''; msg.className='win-message'; } if(tab==='login'){ loginForm.classList.remove('hidden'); signupForm.classList.add('hidden'); tabLogin.classList.add('active'); tabSignup.classList.remove('active'); } else { signupForm.classList.remove('hidden'); loginForm.classList.add('hidden'); tabSignup.classList.add('active'); tabLogin.classList.remove('active'); }}

// Enhance auth tab switching with focus management
const _origSwitchAuthTab = switchAuthTab;
function switchAuthTab(tab){
	const loginForm=document.getElementById('loginForm');
	const signupForm=document.getElementById('signupForm');
	const tabLogin=document.getElementById('tab-login');
	const tabSignup=document.getElementById('tab-signup');
	const msg=document.getElementById('authMessage');
	if(msg){ msg.textContent=''; msg.className='win-message'; }
	if(tab==='login'){
		loginForm.classList.remove('hidden');
		signupForm.classList.add('hidden');
		tabLogin.classList.add('active');
		tabSignup.classList.remove('active');
		focusFirstInput(loginForm);
	} else {
		signupForm.classList.remove('hidden');
		loginForm.classList.add('hidden');
		tabSignup.classList.add('active');
		tabLogin.classList.remove('active');
		focusFirstInput(signupForm);
	}
}
function showNotification(title,message,type='info'){ const container=document.getElementById('notificationContainer'); if(!container) return; const n=document.createElement('div'); n.className=`notification ${type}`; n.innerHTML=`<div class='notification-title'>${title}</div><div class='notification-message'>${message}</div>`; container.appendChild(n); n.addEventListener('click',()=>{ n.classList.add('removing'); setTimeout(()=>n.remove(),300); }); setTimeout(()=>{ n.classList.add('removing'); setTimeout(()=>n.remove(),300); },5000); }
function unlockAchievement(id,title,description){ showNotification(`🏆 ${title}`,description,'success'); createConfetti(); }
function checkDailyBonus(){}
async function initDailyBonusUI(){ const btn=document.getElementById('claimDailyBonusBtn'); if(!btn) return; btn.disabled=true; if(!apiClient.isAuthenticated()||!currentUser){ btn.textContent='Login for Bonus'; return;} try { const profile=await apiClient.getProfile(); const streak=profile.streak||{current_streak:0}; const lastClaim=profile.user.last_bonus_claim||0; const now=Date.now(); const oneDayMs=86400000; if(now-lastClaim>=oneDayMs){ const bonusBase=500+Math.min(streak.current_streak*50,500); btn.textContent=`Claim $${bonusBase}`; btn.disabled=false; btn.onclick= async ()=>{ btn.disabled=true; showLoader(); try { const res=await apiClient.claimDailyBonus(); balance=res.balance; updateBalance(); showNotification('Bonus Claimed',`You received $${res.amount}`,'success'); createConfetti(); } catch(err){ showNotification('Bonus Error',err.message||'Failed','error'); } finally { hideLoader(); initDailyBonusUI(); } }; } else { const remaining=oneDayMs-(now-lastClaim); const hrs=Math.floor(remaining/3600000); const mins=Math.floor((remaining%3600000)/60000); btn.textContent=`Next in ${hrs}h ${mins}m`; } } catch(e){ btn.textContent='Bonus unavailable'; }}
async function renderAchievements(){ const grid=document.getElementById('achievementsGrid'); if(!grid) return; grid.innerHTML=''; if(!apiClient.isAuthenticated()){ grid.innerHTML='<p style="text-align:center;color:var(--text-gray)">Login to view achievements.</p>'; return;} try { const data=await apiClient.getAchievements(); const list=data.achievements||[]; if(!list.length){ grid.innerHTML='<p style="text-align:center;color:var(--text-gray)">No achievements yet.</p>'; return;} list.forEach(a=>{ const d=new Date(a.unlocked_at||Date.now()); const el=document.createElement('div'); el.className='achievement-card unlocked'; el.innerHTML=`<div class='achievement-icon'>🏆</div><div class='achievement-title'>${a.title}</div><div class='achievement-desc'>${a.description}</div><div class='achievement-date'>${d.toLocaleDateString()} ${d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div>`; grid.appendChild(el); }); } catch(e){ grid.innerHTML='<p style="text-align:center;color:var(--text-gray)">Failed to load achievements.</p>'; }}
async function renderLeaderboard(type){ const list=document.getElementById('leaderboardList'); if(!list) return; list.innerHTML='Loading...'; try { const isGame=['slots','roulette','blackjack'].includes(type); const data=await apiClient.getLeaderboard(isGame?'profit':type,isGame?type:null,10); const lb=data.leaderboard||[]; list.innerHTML=''; lb.forEach((row,idx)=>{ const li=document.createElement('li'); const scoreVal=row.net_profit!==undefined?('$'+row.net_profit.toLocaleString()):row.level!==undefined?('Lvl '+row.level):('$'+(row.profit||0).toLocaleString()); li.innerHTML=`<span class='leaderboard-rank'>#${idx+1}</span><span class='leaderboard-name'>${row.username||'Player'}</span><span class='leaderboard-score'>${scoreVal}</span>`; list.appendChild(li); }); } catch(e){ list.innerHTML='<li>Failed to load leaderboard</li>'; } document.querySelectorAll('.leaderboard-tab').forEach(tab=>{ tab.classList.remove('active'); if(tab.dataset.lbType===type) tab.classList.add('active'); tab.onclick=()=>renderLeaderboard(tab.dataset.lbType); }); }
async function renderStats(){ const grid=document.getElementById('statsGrid'); if(!grid) return; grid.innerHTML=''; if(!apiClient.isAuthenticated()){ grid.innerHTML='<p style="text-align:center;color:var(--text-gray)">Login to view stats.</p>'; return;} try { const data=await apiClient.getStats(); const s=data.stats||{}; const breakdown=data.gameBreakdown||[]; const core=[{label:'Total Games',value:s.total_games||0},{label:'Wins',value:s.total_wins||0},{label:'Win Rate',value:(s.winRate||0)+'%'},{label:'Net Profit',value:'$'+(s.net_profit||0).toLocaleString()},{label:'Biggest Win',value:'$'+(s.biggest_win||0).toLocaleString()},{label:'Avg Bet',value:'$'+(Math.round(s.avg_bet)||0).toLocaleString()}]; core.forEach(d=>{ const card=document.createElement('div'); card.className='stat-card'; card.innerHTML=`<div class='stat-label'>${d.label}</div><div class='stat-value'>${d.value}</div>`; grid.appendChild(card); }); breakdown.forEach(gb=>{ const card=document.createElement('div'); card.className='stat-card'; card.innerHTML=`<div class='stat-label'>${gb.game} plays</div><div class='stat-value'>${gb.plays} (Wins: ${gb.wins})</div>`; grid.appendChild(card); }); updateXPBar(); } catch(e){ grid.innerHTML='<p style="text-align:center;color:var(--text-gray)">Failed to load stats.</p>'; }}
function updateXPBar(){ if(!currentUser) return; const xpFill=document.getElementById('xpFill'); const xpValue=document.getElementById('xpValue'); if(!xpFill||!xpValue) return; const xp=currentUser.xp||0; const level=currentUser.level||1; const base=(level-1)*1000; const progress=xp-base; const pct=Math.min(100,(progress/1000)*100); xpFill.style.width=pct+'%'; xpValue.textContent=`${progress} / 1000`; }
function updateXPFromProgression(progression,gained){ if(!progression||!currentUser) return; currentUser.level=progression.level; currentUser.xp=progression.xp; updateUserUI(); updateXPBar(); if(gained) showNotification('XP Gained',`+${gained} XP`,'info'); }
function updateFairness(seed,hash){ const seedEl=document.getElementById('fairnessSeed'); const verifyBtn=document.getElementById('verifyFairnessBtn'); if(seedEl) seedEl.textContent=seed||'—'; if(verifyBtn){ if(seed&&hash){ verifyBtn.disabled=false; verifyBtn.onclick= async ()=>{ try { const res=await apiClient.verifyGame(seed,hash); showNotification('Fairness Check',res.valid?'Valid seed/hash':'Invalid!',res.valid?'success':'error'); } catch(e){ showNotification('Fairness Error',e.message||'Verification failed','error'); } }; } else verifyBtn.disabled=true; }}
function showLoader(){ const l=document.getElementById('globalLoader'); if(l){ l.classList.remove('hidden'); l.setAttribute('aria-hidden','false'); }}
function hideLoader(){ const l=document.getElementById('globalLoader'); if(l){ l.classList.add('hidden'); l.setAttribute('aria-hidden','true'); }}
function initRevealObserver(){ const o=new IntersectionObserver(entries=>{ entries.forEach(en=>{ if(en.isIntersecting){ en.target.classList.add('visible'); o.unobserve(en.target); } }); },{threshold:0.15}); document.querySelectorAll('.reveal').forEach(el=>o.observe(el)); }
function initTiltEffects(){ document.querySelectorAll('.tilt-hover').forEach(el=>{ el.addEventListener('mousemove',e=>{ const r=el.getBoundingClientRect(); const x=e.clientX-r.left; const y=e.clientY-r.top; const rotX=((y/r.height)-0.5)*-10; const rotY=((x/r.width)-0.5)*10; el.style.transform=`perspective(800px) translateY(-8px) rotateX(${rotX}deg) rotateY(${rotY}deg)`; }); el.addEventListener('mouseleave',()=>{ el.style.transform=''; }); }); }
const style=document.createElement('style'); style.textContent='@keyframes confettiFall { to { transform: translateY(100vh) rotate(360deg); opacity: 0; } }'; document.head.appendChild(style);
function createConfetti(){ const colors=['#FFD700','#FF6B6B','#4ECDC4','#45B7D1','#FFA07A']; for(let i=0;i<50;i++){ setTimeout(()=>{ const c=document.createElement('div'); c.style.position='fixed'; c.style.width='10px'; c.style.height='10px'; c.style.backgroundColor=colors[Math.floor(Math.random()*colors.length)]; c.style.left=Math.random()*100+'%'; c.style.top='-10px'; c.style.borderRadius='50%'; c.style.pointerEvents='none'; c.style.zIndex='9999'; c.style.animation=`confettiFall ${2+Math.random()*2}s linear forwards`; document.body.appendChild(c); setTimeout(()=>c.remove(),4000); },i*20); }}
window.spinSlots=spinSlots; window.placeBet=placeBet; window.spinRoulette=spinRoulette; window.dealCards=dealCards; window.hit=hit; window.stand=stand; window.handleLogin=handleLogin; window.handleSignup=handleSignup; window.handleLogout=handleLogout; window.handleDeposit=handleDeposit; window.handleWithdraw=handleWithdraw; window.openGame=openGame; window.closeGame=closeGame; window.openFinance=openFinance; window.closeFinance=closeFinance; window.switchFinanceTab=switchFinanceTab; window.renderLeaderboard=renderLeaderboard; window.scrollToGames=scrollToGames;

function initHeroMetrics(){ const counters=document.querySelectorAll('[data-counter-target]'); if(!counters.length) return; counters.forEach(el=>{ const target=parseFloat(el.dataset.counterTarget); if(isNaN(target)) return; const format=el.dataset.counterFormat||'number'; const prefix=el.dataset.counterPrefix||''; const suffix=el.dataset.counterSuffix||''; const decimals=el.dataset.counterDecimals?parseInt(el.dataset.counterDecimals,10):null; animateCounter(el,target,format,prefix,suffix,decimals); setInterval(()=>{ const variance=target*0.012; const oscillation=target+((Math.random()*2-1)*variance); animateCounter(el,Math.max(0,oscillation),format,prefix,suffix,decimals); },9000+Math.random()*4000); }); }

function animateCounter(el,target,format,prefix,suffix,decimals){ const duration=1200; const startValue=parseFloat(el.dataset.counterValue)||0; const start=performance.now(); const step=now=>{ const progress=Math.min((now-start)/duration,1); const value=startValue+(target-startValue)*progress; el.dataset.counterValue=value; el.textContent=formatCounterValue(value,format,prefix,suffix,decimals); if(progress<1) requestAnimationFrame(step); }; requestAnimationFrame(step); }

function formatCounterValue(value,format,prefix,suffix,decimals){ if(format==='currency'){ return `${prefix}${Math.round(value).toLocaleString()}${suffix||''}`; } if(format==='percent'){ const places=Number.isInteger(decimals)?decimals:1; return `${prefix}${value.toFixed(places)}${suffix||'%'}`; } if(format==='compact'){ const formatter=new Intl.NumberFormat('en', { notation:'compact', maximumFractionDigits:Number.isInteger(decimals)?decimals:1 }); return `${prefix}${formatter.format(value)}${suffix||''}`; } const places=Number.isInteger(decimals)?decimals:0; const formatted=Number(value).toFixed(places).replace(/\B(?=(\d{3})+(?!\d))/g, ','); return `${prefix}${formatted}${suffix||''}`; }

function initLiveTicker(){ const track=document.getElementById('liveTickerTrack'); if(!track) return; const highlights=["🎰 <strong>Slots</strong> Nova hit $18,400 on a 50x combo","🃏 <strong>Blackjack</strong> Celestine pulled a perfect 21","🎲 <strong>Roulette</strong> Table 07 paid 10x on green","💰 <strong>Wallet</strong> VIP deposit processed in 2.3s","🏆 <strong>Leaderboard</strong> AstraNova up $128,400 today","⚡ <strong>Daily Bonus</strong> 6,420 players claimed streaks"]; const markup=highlights.map(item=>`<span class="ticker-item">${item}</span>`).join(''); track.innerHTML=markup+markup; }

function initSpotlightCountdown(){ const countdown=document.querySelector('[data-countdown]'); if(!countdown) return; let targetAttr=countdown.dataset.countdownTarget; let targetDate=targetAttr?new Date(targetAttr):null; if(!targetDate||Number.isNaN(targetDate.getTime())){ targetDate=getFutureDate(36); } const parts={ days:countdown.querySelector('[data-countdown-part="days"]'), hours:countdown.querySelector('[data-countdown-part="hours"]'), minutes:countdown.querySelector('[data-countdown-part="minutes"]'), seconds:countdown.querySelector('[data-countdown-part="seconds"]') }; const format=val=>String(val).padStart(2,'0'); const tick=()=>{ const now=new Date(); let diff=targetDate-now; if(diff<=0){ targetDate=getFutureDate(36); diff=targetDate-now; } const totalSeconds=Math.floor(diff/1000); const days=Math.floor(totalSeconds/86400); const hours=Math.floor((totalSeconds%86400)/3600); const minutes=Math.floor((totalSeconds%3600)/60); const seconds=totalSeconds%60; if(parts.days) parts.days.textContent=format(days); if(parts.hours) parts.hours.textContent=format(hours); if(parts.minutes) parts.minutes.textContent=format(minutes); if(parts.seconds) parts.seconds.textContent=format(seconds); }; tick(); setInterval(tick,1000); }

function getFutureDate(hoursAhead){ const now=new Date(); return new Date(now.getTime()+hoursAhead*60*60*1000); }

function initHeatmapBars(){ const bars=document.querySelectorAll('.heatmap-bar'); if(!bars.length) return; bars.forEach((bar,idx)=>{ const value=Math.max(0,Math.min(100,parseInt(bar.dataset.heatValue,10)||0)); const fill=bar.querySelector('.heatmap-fill'); const label=bar.querySelector('.heatmap-value'); if(label) label.textContent=`${value}%`; requestAnimationFrame(()=>{ setTimeout(()=>{ if(fill) fill.style.width=value+'%'; }, idx*120); }); }); }

